version: '2'

services:
  web:
    image: php:7.2-apache
    environment:
       - ALLOW_OVERRIDE=true
    ports:
       - "80:80"
    links:
       - db
    volumes:
       - ./app:/var/www/html/

  db:
    image: postgres:9.4
    ports:
       - 5432:5432
    environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_DB=tpweb
    volumes:
       - /data/postgres:/var/lib/postgresql/data
